#############################################################################
# Makefile for building: 360Safe
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Aug 26 17:33:32 2014
# Project:  360Safe.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile 360Safe.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = about_us.cpp \
		change_skin_widget.cpp \
		character_widget.cpp \
		clabel.cpp \
		content_widget.cpp \
		main.cpp \
		main_menu.cpp \
		main_widget.cpp \
		push_button.cpp \
		setting_dialog.cpp \
		skin_widget.cpp \
		skinwidget.cpp \
		system_tray.cpp \
		title_widget.cpp \
		tool_button.cpp \
		util.cpp moc_about_us.cpp \
		moc_change_skin_widget.cpp \
		moc_character_widget.cpp \
		moc_clabel.cpp \
		moc_content_widget.cpp \
		moc_main_menu.cpp \
		moc_main_widget.cpp \
		moc_push_button.cpp \
		moc_setting_dialog.cpp \
		moc_skin_widget.cpp \
		moc_skinwidget.cpp \
		moc_system_tray.cpp \
		moc_title_widget.cpp \
		qrc_QRC.cpp
OBJECTS       = about_us.o \
		change_skin_widget.o \
		character_widget.o \
		clabel.o \
		content_widget.o \
		main.o \
		main_menu.o \
		main_widget.o \
		push_button.o \
		setting_dialog.o \
		skin_widget.o \
		skinwidget.o \
		system_tray.o \
		title_widget.o \
		tool_button.o \
		util.o \
		moc_about_us.o \
		moc_change_skin_widget.o \
		moc_character_widget.o \
		moc_clabel.o \
		moc_content_widget.o \
		moc_main_menu.o \
		moc_main_widget.o \
		moc_push_button.o \
		moc_setting_dialog.o \
		moc_skin_widget.o \
		moc_skinwidget.o \
		moc_system_tray.o \
		moc_title_widget.o \
		qrc_QRC.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		360Safe.pro
QMAKE_TARGET  = 360Safe
DESTDIR       = 
TARGET        = 360Safe

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 360Safe.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile 360Safe.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile 360Safe.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/360Safe1.0.0 || $(MKDIR) .tmp/360Safe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/360Safe1.0.0/ && $(COPY_FILE) --parents about_us.h change_skin_widget.h character_widget.h clabel.h common.h content_widget.h main_menu.h main_widget.h push_button.h resource.h setting_dialog.h skin_widget.h skinwidget.h system_tray.h title_widget.h tool_button.h util.h .tmp/360Safe1.0.0/ && $(COPY_FILE) --parents QRC.qrc .tmp/360Safe1.0.0/ && $(COPY_FILE) --parents about_us.cpp change_skin_widget.cpp character_widget.cpp clabel.cpp content_widget.cpp main.cpp main_menu.cpp main_widget.cpp push_button.cpp setting_dialog.cpp skin_widget.cpp skinwidget.cpp system_tray.cpp title_widget.cpp tool_button.cpp util.cpp .tmp/360Safe1.0.0/ && $(COPY_FILE) --parents 360safe_en.ts 360safe_zh.ts .tmp/360Safe1.0.0/ && (cd `dirname .tmp/360Safe1.0.0` && $(TAR) 360Safe1.0.0.tar 360Safe1.0.0 && $(COMPRESS) 360Safe1.0.0.tar) && $(MOVE) `dirname .tmp/360Safe1.0.0`/360Safe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/360Safe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_about_us.cpp moc_change_skin_widget.cpp moc_character_widget.cpp moc_clabel.cpp moc_content_widget.cpp moc_main_menu.cpp moc_main_widget.cpp moc_push_button.cpp moc_setting_dialog.cpp moc_skin_widget.cpp moc_skinwidget.cpp moc_system_tray.cpp moc_title_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about_us.cpp moc_change_skin_widget.cpp moc_character_widget.cpp moc_clabel.cpp moc_content_widget.cpp moc_main_menu.cpp moc_main_widget.cpp moc_push_button.cpp moc_setting_dialog.cpp moc_skin_widget.cpp moc_skinwidget.cpp moc_system_tray.cpp moc_title_widget.cpp
moc_about_us.cpp: push_button.h \
		about_us.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) about_us.h -o moc_about_us.cpp

moc_change_skin_widget.cpp: change_skin_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) change_skin_widget.h -o moc_change_skin_widget.cpp

moc_character_widget.cpp: push_button.h \
		clabel.h \
		common.h \
		character_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) character_widget.h -o moc_character_widget.cpp

moc_clabel.cpp: clabel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clabel.h -o moc_clabel.cpp

moc_content_widget.cpp: content_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) content_widget.h -o moc_content_widget.cpp

moc_main_menu.cpp: main_menu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) main_menu.h -o moc_main_menu.cpp

moc_main_widget.cpp: title_widget.h \
		push_button.h \
		tool_button.h \
		content_widget.h \
		system_tray.h \
		about_us.h \
		main_menu.h \
		character_widget.h \
		clabel.h \
		common.h \
		setting_dialog.h \
		skin_widget.h \
		change_skin_widget.h \
		main_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) main_widget.h -o moc_main_widget.cpp

moc_push_button.cpp: push_button.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) push_button.h -o moc_push_button.cpp

moc_setting_dialog.cpp: push_button.h \
		setting_dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) setting_dialog.h -o moc_setting_dialog.cpp

moc_skin_widget.cpp: push_button.h \
		change_skin_widget.h \
		skin_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) skin_widget.h -o moc_skin_widget.cpp

moc_skinwidget.cpp: skinwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) skinwidget.h -o moc_skinwidget.cpp

moc_system_tray.cpp: system_tray.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) system_tray.h -o moc_system_tray.cpp

moc_title_widget.cpp: push_button.h \
		tool_button.h \
		title_widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) title_widget.h -o moc_title_widget.cpp

compiler_rcc_make_all: qrc_QRC.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QRC.cpp
qrc_QRC.cpp: QRC.qrc \
		img/mainMenu/help.png \
		img/mainMenu/about.png \
		img/mainMenu/setting.png \
		img/mainMenu/update.png \
		img/mainMenu/home.png \
		img/toolWidget/gongNeng.png \
		img/toolWidget/menZhen.png \
		img/toolWidget/xiTong.png \
		img/toolWidget/muMa.png \
		img/toolWidget/jiaSu.png \
		img/toolWidget/qingLi.png \
		img/toolWidget/louDong.png \
		img/toolWidget/ruanJian.png \
		img/toolWidget/tiJian.png \
		img/skin/10_big.png \
		img/skin/7_big.png \
		img/skin/17_big.jpg \
		img/skin/1_big.png \
		img/skin/11_big.png \
		img/skin/8_big.png \
		img/skin/18_big.jpg \
		img/skin/2_big.png \
		img/skin/12_big.png \
		img/skin/9_big.png \
		img/skin/19_big.jpg \
		img/skin/20_big.jpg \
		img/skin/10.png \
		img/skin/3_big.png \
		img/skin/11.png \
		img/skin/13_big.png \
		img/skin/12.png \
		img/skin/13.png \
		img/skin/14.png \
		img/skin/15.jpg \
		img/skin/16.jpg \
		img/skin/17.jpg \
		img/skin/18.jpg \
		img/skin/21_big.jpg \
		img/skin/19.jpg \
		img/skin/4_big.png \
		img/skin/14_big.png \
		img/skin/20.jpg \
		img/skin/21.jpg \
		img/skin/22.jpg \
		img/skin/22_big.jpg \
		img/skin/23.jpg \
		img/skin/0.png \
		img/skin/1.png \
		img/skin/5_big.png \
		img/skin/2.png \
		img/skin/15_big.jpg \
		img/skin/3.png \
		img/skin/4.png \
		img/skin/5.png \
		img/skin/6.png \
		img/skin/7.png \
		img/skin/8.png \
		img/skin/23_big.jpg \
		img/skin/9.png \
		img/skin/6_big.png \
		img/skin/16_big.jpg \
		img/skin/0_big.png \
		img/logo.png \
		img/360safe.png \
		img/safe.png \
		img/contentWidget/mobile.png \
		img/contentWidget/medal_light.png \
		img/contentWidget/priv.png \
		img/contentWidget/game_box.png \
		img/contentWidget/lottery.png \
		img/contentWidget/net_repair.png \
		img/contentWidget/tab.png \
		img/contentWidget/medal.png \
		img/contentWidget/cloud.png \
		img/contentWidget/computer.png \
		img/contentWidget/version.png \
		img/contentWidget/login.png \
		img/contentWidget/auto_run.png \
		img/contentWidget/net_pretext.png \
		img/contentWidget/net_speed.png \
		img/contentWidget/power.png \
		img/contentWidget/fireproof.png \
		img/contentWidget/360.png \
		img/contentWidget/desktop.png \
		img/contentWidget/recovery.png \
		img/contentWidget/caipiao.png \
		img/contentWidget/pet.png \
		img/contentWidget/first_add.png \
		img/contentWidget/triggerman.png \
		img/contentWidget/cloud_five.png \
		img/contentWidget/net_shop.png \
		qt_zh_CN.qm \
		360safe_en.qm \
		360safe_zh.qm \
		img/sysButton/max_button.png \
		img/sysButton/close_button.png \
		img/sysButton/close.png \
		img/sysButton/skin_button.png \
		img/sysButton/main_menu.png \
		img/sysButton/min_button.png \
		img/newCharacter/desktop_0.jpg \
		img/newCharacter/desktop_1.jpg \
		img/newCharacter/desktop_2.jpg \
		img/newCharacter/bg_bottom.png \
		img/newCharacter/desktop_3.jpg \
		img/newCharacter/btn_open.png \
		img/newCharacter/btn_use.png \
		img/newCharacter/bg_top.png \
		img/newCharacter/btn_0.png \
		img/newCharacter/btn_1.png \
		img/newCharacter/btn_2.png \
		img/newCharacter/btn_3.png \
		img/newCharacter/bg_briangle.png
	/usr/bin/rcc -name QRC QRC.qrc -o qrc_QRC.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

about_us.o: about_us.cpp about_us.h \
		push_button.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about_us.o about_us.cpp

change_skin_widget.o: change_skin_widget.cpp change_skin_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o change_skin_widget.o change_skin_widget.cpp

character_widget.o: character_widget.cpp character_widget.h \
		push_button.h \
		clabel.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character_widget.o character_widget.cpp

clabel.o: clabel.cpp clabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clabel.o clabel.cpp

content_widget.o: content_widget.cpp content_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o content_widget.o content_widget.cpp

main.o: main.cpp main_widget.h \
		title_widget.h \
		push_button.h \
		tool_button.h \
		content_widget.h \
		system_tray.h \
		about_us.h \
		main_menu.h \
		character_widget.h \
		clabel.h \
		common.h \
		setting_dialog.h \
		skin_widget.h \
		change_skin_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_menu.o: main_menu.cpp main_menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_menu.o main_menu.cpp

main_widget.o: main_widget.cpp main_widget.h \
		title_widget.h \
		push_button.h \
		tool_button.h \
		content_widget.h \
		system_tray.h \
		about_us.h \
		main_menu.h \
		character_widget.h \
		clabel.h \
		common.h \
		setting_dialog.h \
		skin_widget.h \
		change_skin_widget.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_widget.o main_widget.cpp

push_button.o: push_button.cpp push_button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o push_button.o push_button.cpp

setting_dialog.o: setting_dialog.cpp setting_dialog.h \
		push_button.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setting_dialog.o setting_dialog.cpp

skin_widget.o: skin_widget.cpp skin_widget.h \
		push_button.h \
		change_skin_widget.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skin_widget.o skin_widget.cpp

skinwidget.o: skinwidget.cpp skinwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skinwidget.o skinwidget.cpp

system_tray.o: system_tray.cpp system_tray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o system_tray.o system_tray.cpp

title_widget.o: title_widget.cpp title_widget.h \
		push_button.h \
		tool_button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o title_widget.o title_widget.cpp

tool_button.o: tool_button.cpp tool_button.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tool_button.o tool_button.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

moc_about_us.o: moc_about_us.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about_us.o moc_about_us.cpp

moc_change_skin_widget.o: moc_change_skin_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_change_skin_widget.o moc_change_skin_widget.cpp

moc_character_widget.o: moc_character_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_character_widget.o moc_character_widget.cpp

moc_clabel.o: moc_clabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clabel.o moc_clabel.cpp

moc_content_widget.o: moc_content_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_content_widget.o moc_content_widget.cpp

moc_main_menu.o: moc_main_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_menu.o moc_main_menu.cpp

moc_main_widget.o: moc_main_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_widget.o moc_main_widget.cpp

moc_push_button.o: moc_push_button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_push_button.o moc_push_button.cpp

moc_setting_dialog.o: moc_setting_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setting_dialog.o moc_setting_dialog.cpp

moc_skin_widget.o: moc_skin_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_skin_widget.o moc_skin_widget.cpp

moc_skinwidget.o: moc_skinwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_skinwidget.o moc_skinwidget.cpp

moc_system_tray.o: moc_system_tray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_system_tray.o moc_system_tray.cpp

moc_title_widget.o: moc_title_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_title_widget.o moc_title_widget.cpp

qrc_QRC.o: qrc_QRC.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QRC.o qrc_QRC.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

